from django.db import models


class Department(models.Model):
    #id is autogenerated
    name = models.CharField(max_length=100, null=False)
    description = models.CharField(max_length=300, null=False)
    location = models.CharField(max_length=50, null=True)
    pin_code = models.CharField(max_length=10, default="522613")
    date_created = models.DateTimeField(auto_now=True)
    date_updated = models.DateTimeField(null=True)


class Employee(models.Model):
    name = models.CharField(max_length=100, null=False)
    dob = models.DateField(null=False)
    salary = models.IntegerField(null=False)
    address = models.CharField(max_length=200, null=False)
    date_created = models.DateTimeField(auto_now=True)
    date_updated = models.DateTimeField(null=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)


class Inventory(models.Model):
    item = models.CharField(max_length=20)
    item_code = models.IntegerField()
    item_condition = models.CharField(max_length=50)
    quantity = models.IntegerField()

    def __str__(self):
        return self.item


class Contact(models.Model):
    name = models.CharField(max_length=100, null=False)
    email = models.EmailField(null=False)
    phone_number = models.CharField(max_length=10, null=False)
    comments = models.TextField(null=False)


class Friend(models.Model):
    # NICK NAME should be unique
    nick_name = models.CharField(max_length=100, unique = True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    likes = models.CharField(max_length=250)
    dob = models.DateField(auto_now=False, auto_now_add=False)
    lives_in = models.CharField(max_length=150, null=True, blank=True)
    def __str__(self):
        return self.nick_name






