# Generated by Django 2.1 on 2021-02-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_department_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='pin_code',
            field=models.CharField(default='522613', max_length=10),
        ),
    ]
